// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddxeiqwrleookizoqfhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkeGVpcXdybGVvb2tpem9xZmhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MjgxOTgsImV4cCI6MjA3MzQwNDE5OH0.3tKXRRmclW8ZttQAxWVkjUqi0X_AkS6rMgH1cBC1dDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});